[workspace]
resolver = "2"
members=[
    # Core libraries
    "music-notes",
    "midi-events",
    "midi-device",

    # Module libraries.
    "jack-module",
    "egui-widgets-music",

    # Applications.
    "jack-midi-logger",
    "jack-midi-transposer",
    "demo-test",
]