[package]
name = "midi-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midi-events = {path="../midi-events"}
music-notes = {path="../music-notes"}
