[package]
name = "demo-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu={version="0.15.1", features=["glsl"]}
naga = {version="0.11"}
pollster={version="0.2"}
winit={version="0.27.1"}
